spring.application.name=ShoppingListServices
spring.datasource.url=jdbc:mariadb://localhost:3306/shopping_list_users_db
spring.datasource.driverClassName=org.mariadb.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

server.port=4443
spring.jpa.properties.hibernate.format_sql=true
spring.threads.virtual.enabled=true
logging.file.name=logs/application.log
server.servlet.encoding.enabled=true

spring.flyway.url=jdbc:mariadb://localhost:3306/shopping_list_users_db
spring.flyway.driver-class-name=org.mariadb.jdbc.Driver

management.endpoints.enabled-by-default=false



